databaseChangeLog:
  - property:
      name: environment_name
      value: uat
  - property:
      name: datashare_name
      value: uat_sales_share
  - includeAll:
      path: migrations/
      relativeToChangelogFile: true
