clusters:
  - target:
      host: "uat-producer.abcdefg.us-east-1.redshift.amazonaws.com"
      port: 5439
      database: "uat_db"
      liquibase_contexts: "producer"
    users:
      dbt_user:
        roles:
          - dbt_transformer
    roles:
      dbt_transformer:
        permissions:
          - write_campaigns
          - full_schema_access
    permissions:
      write_campaigns:
        resource_type: table
        privileges:
          - ALL
        entities:
          - "marketing.*"
          - "sales.*"

      full_schema_access:
        resource_type: schema
        privileges:
          - ALL
        entities:
          - "analytics"

  - target:
      host: "uat-consumer.abcdefg.us-east-1.redshift.amazonaws.com"
      port: 5439
      database: "uat_db"
      liquibase_contexts: "consumer"
    users:
      bi_user:
        roles:
          - bi_analyst
    roles:
      bi_analyst:
        permissions:
          - read_all_models
    permissions:
      read_all_models:
        resource_type: table
        privileges:
          - SELECT
        entities:
          - "analytics.*"
