clusters:
  - target:
      host: "dev-cluster-1.abcdefg.us-east-1.redshift.amazonaws.com"
      port: 5439
      database: "dev_db"
    users:
      jane_doe:
        roles:
          - marketing_analyst
    roles:
      marketing_analyst:
        permissions:
          - read_campaigns
    permissions:
      read_campaigns:
        resource_type: table
        privileges:
          - SELECT
        entities:
          - "marketing.campaigns"

  - target:
      host: "dev-cluster-2.abcdefg.us-east-1.redshift.amazonaws.com"
      port: 5439
      database: "dev_db"
    users:
      bob_smith:
        roles:
          - data_scientist
    roles:
      data_scientist:
        permissions:
          - read_all_models
    permissions:
      read_all_models:
        resource_type: model
        privileges:
          - EXECUTE
        entities:
          - "ml.*"
